name: LelBot dev CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:

    environment: dev
    runs-on: newton
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
           name: "config.json"
           json: '{"token": "${{ secrets.DISCORD_TOKEN }}", "clientId": "${{ secrets.DISCORD_APP_ID }}", "guildId": "${{ secrets.DISCORD_DEV_GUILD_ID }}"}'

#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
      
#      - run: npm install pm2@latest -g
      
      - run: npm install
      
      ### hotfix, bug in glob
      - run: npm install --save glob
      ###

      - run: pm2 delete ${{ secrets.BOT_DEPLOYMENT_NAME }} 2> /dev/null || true

      - run: node deploy-commands.js 2> /dev/null || true

      - run: RUNNER_TRACKING_ID="${{ secrets.BOT_DEPLOYMENT_NAME }}" && (nohup pm2 start index.js --node-args="--status ${{ secrets.DISCORD_STATUS }} --activity-type ${{ secrets.DISCORD_ACTIVITY_TYPE }} --activity-name '${{ secrets.DISCORD_ACTIVITY_NAME }}'" -i 1 -f --name ${{ secrets.BOT_DEPLOYMENT_NAME }}&)

      - run: pm2 save
