name: LelBot prod CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_on_prod:

    environment: prod
    runs-on: galileo
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
           name: "config.json"
           json: '{"token":"${{ secrets.DISCORD_TOKEN }}"}'

#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
      
#      - run: npm install pm2@latest -g
      
      - run: npm install
      
      ### hotfix, bug in glob
      - run: npm install --save glob
      ###

      - run: pm2 delete lelbot 2> /dev/null || true

      - run: RUNNER_TRACKING_ID="lelbot_prod" && (nohup pm2 start index.js -i 1 -f --name lelbot&)

      - run: pm2 save
